# Generated by Django 4.0.6 on 2022-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_marker_address_marker_auditive_marker_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='repsolSun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
