# Generated by Django 4.0.6 on 2022-07-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(blank=True, max_length=255, null=True)),
                ('documentDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('templateType', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('qualityQ', models.CharField(blank=True, max_length=255, null=True)),
                ('qualityIconDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('physical', models.CharField(blank=True, max_length=255, null=True)),
                ('visual', models.CharField(blank=True, max_length=255, null=True)),
                ('auditive', models.CharField(blank=True, max_length=255, null=True)),
                ('intellectual', models.CharField(blank=True, max_length=255, null=True)),
                ('organic', models.CharField(blank=True, max_length=255, null=True)),
                ('tourismEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('natureType', models.CharField(blank=True, max_length=255, null=True)),
                ('latitudelongitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latwgs84', models.CharField(blank=True, max_length=255, null=True)),
                ('lonwgs84', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('municipalitycode', models.CharField(blank=True, max_length=255, null=True)),
                ('territory', models.CharField(blank=True, max_length=255, null=True)),
                ('territorycode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('countrycode', models.CharField(blank=True, max_length=255, null=True)),
                ('friendlyUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('physicalUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('dataXML', models.CharField(blank=True, max_length=255, null=True)),
                ('metadataXML', models.CharField(blank=True, max_length=255, null=True)),
                ('zipFile', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
