# Generated by Django 4.0.6 on 2022-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_comment_qualityprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='complementPlan',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.IntegerField(choices=[(1, 'Mal / Gaizki'), (2, 'Suficiente / Nahikoa'), (3, 'Bien / Ondo'), (4, 'Muy bien / Oso ondo'), (5, 'Excelente / Bikain')], default=3),
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.IntegerField(choices=[(1, 'Mal / Gaizki'), (2, 'Suficiente / Nahikoa'), (3, 'Bien / Ondo'), (4, 'Muy bien / Oso ondo'), (5, 'Excelente / Bikain')], default=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='qualityPrice',
            field=models.IntegerField(choices=[(1, 'Mal / Gaizki'), (2, 'Suficiente / Nahikoa'), (3, 'Bien / Ondo'), (4, 'Muy bien / Oso ondo'), (5, 'Excelente / Bikain')], default=3),
        ),
    ]
