# Generated by Django 4.0.6 on 2022-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment_complementplan_comment_food_comment_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='complementPlan',
            new_name='complementCulturePlan',
        ),
        migrations.AddField(
            model_name='comment',
            name='complementNaturePlan',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='complementOtherPlan',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
